In [23]:
import pandas as pd

In [24]:
import sqlite3

In [25]:
import matplotlib.pyplot as plt
% matplotlib inline

In [26]:
import seaborn as sns

In [27]:
con = sqlite3.connect("clues.db")

In [28]:
jeopardy_data = pd.read_sql("SELECT clues.id, clues.game, airdate, round, value, category, clue, answer FROM clues JOIN airdates ON clues.game = airdates.game JOIN documents ON clues.id = documents.id JOIN classifications ON clues.id = classifications.clue_id JOIN categories ON classifications.category_id = categories.id", con)

In [29]:
jeopardy_data.head()

,id,game,airdate,round,value,category,clue,answer
0,1,1,2004-09-06,1,200,THE OLD TESTAMENT,"Let's all flock to read Psalm 95, in which hum...",sheep
1,2,1,2004-09-06,1,200,SEAN SONG,"The rap on him is he's sometimes ""Puffy""",Sean Combs
2,3,1,2004-09-06,1,200,CITY WALK,In the 1980s this city passed Chicago as the U...,Los Angeles
3,4,1,2004-09-06,1,200,SLOGANEERING,"""Ask any mermaid you happen to see, 'What's th...",Chicken of the Sea
4,5,1,2004-09-06,1,200,ROOM,"Many people have become familiar with ""Shape"",...",magazines

In [30]:
jeopardy_data.count()

id          330563
game        330563
airdate     330563
round       330563
value       330563
category    330563
clue        330563
answer      330563
dtype: int64

In [31]:
jeopardy_data.isnull().sum()

id          0
game        0
airdate     0
round       0
value       0
category    0
clue        0
answer      0
dtype: int64

In [32]:
jeopardy_data["round"].value_counts()

1    163522
2    161484
3      5557
Name: round, dtype: int64

Hypothesis/Problem Statement: In this analysis I am going to be looking at historical Jeopardy data to determine which topics appear most frequently and are the most valuable. I hypothesize that history will be the most frequent and valuable topic.

In [33]:
jeopardy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330563 entries, 0 to 330562
Data columns (total 8 columns):
id          330563 non-null int64
game        330563 non-null int64
airdate     330563 non-null object
round       330563 non-null int64
value       330563 non-null object
category    330563 non-null object
clue        330563 non-null object
answer      330563 non-null object
dtypes: int64(3), object(5)
memory usage: 20.2+ MB

In [12]:
values = jeopardy_data["value"].tolist

In [16]:
import locale
jeopardy_data['value']
#.apply(locale.atof)
#jeopardy_data.head()

0           200
1           200
2           200
3           200
4           200
5           200
6           400
7           400
8           400
9           400
10          400
11          400
12          600
13          600
14          600
15          600
16        4,000
17          600
18          800
19          800
20          800
21          800
22          800
23          800
24         1000
25         1000
26         1000
27         1000
28         1000
29         1000
          ...
330533      500
330534      200
330535      200
330536      200
330537      200
330538      200
330539      200
330540      400
330541      400
330542      400
330543      400
330544      400
330545      400
330546      600
330547      600
330548      600
330549    1,000
330550      600
330551      600
330552      800
330553    2,000
330554      800
330555      800
330556      800
330557     1000
330558     1000
330559     1000
330560     1000
330561     1000
330562        0
Name: value, dtype: object

In [35]:
# a.replace(',','')
jeopardy_data["value"] = jeopardy_data["value"].replace(',','')
jeopardy_data

,id,game,airdate,round,value,category,clue,answer
0,1,1,2004-09-06,1,200,THE OLD TESTAMENT,"Let's all flock to read Psalm 95, in which hum...",sheep
1,2,1,2004-09-06,1,200,SEAN SONG,"The rap on him is he's sometimes ""Puffy""",Sean Combs
2,3,1,2004-09-06,1,200,CITY WALK,In the 1980s this city passed Chicago as the U...,Los Angeles
3,4,1,2004-09-06,1,200,SLOGANEERING,"""Ask any mermaid you happen to see, 'What's th...",Chicken of the Sea
4,5,1,2004-09-06,1,200,ROOM,"Many people have become familiar with ""Shape"",...",magazines
5,6,1,2004-09-06,1,200,"""BOARD""","In 2003, Roy E. Disney left it after being on ...",the Disney Board of Directors
6,7,1,2004-09-06,1,400,THE OLD TESTAMENT,Some say the screech owl in the King James Bib...,Adam
7,8,1,2004-09-06,1,400,SEAN SONG,Once married to Madonna,Sean Penn
8,9,1,2004-09-06,1,400,CITY WALK,"This London borough is the G in GMT, squire",Greenwich
9,10,1,2004-09-06,1,400,SLOGANEERING,"A fast food chain: ""If it doesn't get all over...",Carl's Jr.
10,11,1,2004-09-06,1,400,ROOM,(Cheryl of the Clue Crew reports from the Brie...,Franklin Delano Roosevelt
11,12,1,2004-09-06,1,400,"""BOARD""",It's where Bart Simpson is often found in the ...,his skateboard (or the blackboard)
12,13,1,2004-09-06,1,600,THE OLD TESTAMENT,"Hagar, carrying this man's baby, fled into the...",Abraham
13,14,1,2004-09-06,1,600,SEAN SONG,"He won an Oscar for ""The Untouchables""",Sean Connery
14,15,1,2004-09-06,1,600,CITY WALK,Thomas Alsgaard won the 15-kilometer cross-cou...,Nagano
15,16,1,2004-09-06,1,600,SLOGANEERING,"""Pardon me, but do you have any"" of this fancy...",Grey Poupon
16,17,1,2004-09-06,1,"4,000",ROOM,The Titanic has 3 rooms for this--only men wer...,smoking
17,18,1,2004-09-06,1,600,"""BOARD""",At this time we'd like to do this for our firs...,pre-board
18,19,1,2004-09-06,1,800,THE OLD TESTAMENT,"According to this Old Testament book, this ""sw...",Isaiah
19,20,1,2004-09-06,1,800,SEAN SONG,Yoko's boy,Sean Lennon
20,21,1,2004-09-06,1,800,CITY WALK,"The Dalai Lama's former residence, the Potala ...",Lhasa
21,22,1,2004-09-06,1,800,SLOGANEERING,"""Kiss a little longer"" with this gum",Big Red
22,23,1,2004-09-06,1,800,ROOM,"Officially released in 1975, much-bootlegged t...",the basement
23,24,1,2004-09-06,1,800,"""BOARD""",A structural material named for its small wood...,particle board
24,25,1,2004-09-06,1,1000,THE OLD TESTAMENT,"In Genesis, Joseph is imprisoned after accusat...",Potiphar
25,26,1,2004-09-06,1,1000,SEAN SONG,"Android hottie in ""Blade Runner""",Sean Young
26,27,1,2004-09-06,1,1000,CITY WALK,"Founded by Ram Das, this city in Punjab state ...",Amritsar
27,28,1,2004-09-06,1,1000,SLOGANEERING,The slogan of this Johnson & Johnson product w...,Shower to Shower
28,29,1,2004-09-06,1,1000,ROOM,"Decorating experts, & the film ""The Big Lebows...",a rug
29,30,1,2004-09-06,1,1000,"""BOARD""",(Jimmy of the Clue Crew reads from the Cirque ...,a teeterboard
...,...,...,...,...,...,...,...,...
330533,330534,5655,2001-10-11,1,500,VICE PRESIDENTIAL RHYME TIME,Arthur's fools,Chester's jesters
330534,330535,5655,2001-10-11,2,200,HOW SUITE IT IS,"Debussy's ""Suite Bergamasque"" for piano contai...","""Clair de Lune"""
330535,330536,5655,2001-10-11,2,200,DICKENS' WORKS,"Character who is ""A squeezing, wrenching, scra...",Ebenezer Scrooge
330536,330537,5655,2001-10-11,2,200,BIG SCREEN BOXERS,"Robert De Niro,1980",Jake LaMotta
330537,330538,5655,2001-10-11,2,200,METHODISM,"An important part of services, they include ""O...",hymns
330538,330539,5655,2001-10-11,2,200,HISTORIC WOMEN,You're on the money if you know she's the hist...,Sacajawea
330539,330540,5655,2001-10-11,2,200,NEWER WORDS & PHRASES,"(Sarah, with the rest of the Clue Crew, report...",road rage
330540,330541,5655,2001-10-11,2,400,HOW SUITE IT IS,"""Black, Brown and Beige"" is a 1943 suite by th...",Duke Ellington
330541,330542,5655,2001-10-11,2,400,DICKENS' WORKS,This novel was based in part on Thomas Carlyle...,A Tale of Two Cities
330542,330543,5655,2001-10-11,2,400,BIG SCREEN BOXERS,"Sly Stallone,1976",Rocky Balboa
330543,330544,5655,2001-10-11,2,400,METHODISM,A believer's faith is confirmed by witness of ...,holy spirit
330544,330545,5655,2001-10-11,2,400,HISTORIC WOMEN,She's the famous American folk artist seen here,Grandma Moses
330545,330546,5655,2001-10-11,2,400,NEWER WORDS & PHRASES,"Often applied to Howard Stern, this rhyming te...",shock jock
330546,330547,5655,2001-10-11,2,600,HOW SUITE IT IS,Tchaikovsky simultaneously composed early sket...,The Nutcracker Suite
330547,330548,5655,2001-10-11,2,600,DICKENS' WORKS,"Dickens' 13th novel, it made its world debut i...",Great Expectations
330548,330549,5655,2001-10-11,2,600,BIG SCREEN BOXERS,"Mr. T,1982",Clubber Lang
330549,330550,5655,2001-10-11,2,"1,000",METHODISM,Methodism began as part of this Christian chur...,Anglican Church (Church of England)
330550,330551,5655,2001-10-11,2,600,HISTORIC WOMEN,No one ever said this Revolutionary War-era wo...,Molly Pitcher
330551,330552,5655,2001-10-11,2,600,NEWER WORDS & PHRASES,7-letter synonym listed by the American Herita...,ebonics
330552,330553,5655,2001-10-11,2,800,HOW SUITE IT IS,"Not to tell tales out of school, but the symph...",Scheherazade
330553,330554,5655,2001-10-11,2,"2,000",DICKENS' WORKS,Dickens' first installment of this novel was p...,The Mystery of Edwin Drood
330554,330555,5655,2001-10-11,2,800,BIG SCREEN BOXERS,"Paul Newman,1956",Rocky Graziano
330555,330556,5655,2001-10-11,2,800,HISTORIC WOMEN,In the 1950s this 2-time Wimbledon winner seen...,Althea Gibson
330556,330557,5655,2001-10-11,2,800,NEWER WORDS & PHRASES,This verb meaning to die was further populariz...,flatline
330557,330558,5655,2001-10-11,2,1000,HOW SUITE IT IS,He got around: he wrote suites for Mississippi...,Ferde Grofe
330558,330559,5655,2001-10-11,2,1000,DICKENS' WORKS,"The first play from this book, done while the ...",The Old Curiosity Shop
330559,330560,5655,2001-10-11,2,1000,BIG SCREEN BOXERS,"Marlon Brando,1954",Terry Malloy
330560,330561,5655,2001-10-11,2,1000,HISTORIC WOMEN,She's the courageous schoolteacher shown here,Christa McAuliffe
330561,330562,5655,2001-10-11,2,1000,NEWER WORDS & PHRASES,"From the Latin for ""hear"" & the Greek for ""lov...",audiophile
330562,330563,5655,2001-10-11,3,0,U.S. COLLEGES,Its original home was built in 1829 as an arse...,The Citadel (the Military College of South Car...

In [ ]:
jeopardy_data.head()

In [ ]:
values

In [ ]:
a = '1,000'
int(a.replace(',',''))

In [ ]:
jeopardy_data.dtypes

In [ ]:
jeopardy_data["value"] = pd.to_numeric(jeopardy_data["value"])

In [ ]:
jeopardy_data["value"] = jeopardy_data["value"].replace(",", "").astype(int)

In [ ]:
jeopardy_data.head()

In [ ]:
jeopardy_data.groupby("round").value.mean()

In [ ]:
description = jeopardy_data.groupby("round").sum()

In [ ]:
description